# Parameters for the module names, gains, hrdf, etc
names: [ "J1_shoulder", "J2_elbow" ] # X-80931  J1_shoulder
families: [ "Arm" ] # X8-9  Arm
gains_package: "hebi_cpp_api_examples"
gains_file: "config/gains/flobot_gains.xml"
hrdf_package: "hebi_cpp_api_examples"
hrdf_file: "config/hrdf/flobot.hrdf"
home_position: [ -1.0, 0.0 ]

# Note: the "moveit_joints" must matches the configuration from the MoveIt config; only
# required when running MoveIt examples
moveit_joints: ["Arm/J1_shoulder", "Arm/J2_elbow"]
