# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Arm/J1_base:
    has_velocity_limits: true
    max_velocity: 3.351
    has_acceleration_limits: false
    max_acceleration: 0
  Arm/J2_shoulder:
    has_velocity_limits: true
    max_velocity: 1.466
    has_acceleration_limits: false
    max_acceleration: 0
  Arm/J3_elbow:
    has_velocity_limits: true
    max_velocity: 3.351
    has_acceleration_limits: false
    max_acceleration: 0
  Arm/J4_wrist:
    has_velocity_limits: true
    max_velocity: 9.425000000000001
    has_acceleration_limits: false
    max_acceleration: 0